from copy import deepcopy


DEFAULT_CONFIG = {
    "world": {
        "material": "G4_Galactic",
        "size_x_mm": 300.0,
        "size_y_mm": 300.0,
        "size_z_mm": 300.0,
    },
    "custom_materials": [
        {
            "material_name": "CuWCollimator",
            "density_g_cm3": 9.0,
            "composition": "Cu:0.5,W:0.5",
        }
    ],
    "sample": {
        "name": "sample",
        "shape": "Rectangular",
        "material": "G4_Fe",
        "width_mm": 10.0,
        "height_mm": 10.0,
        "radius_mm": 5.0,
        "thickness_mm": 0.1,
    },
    "tube": {
        "name": "xrftube",
        "current_ma": 1.0,
        "voltage_kv": 50.0,
        "anode_angle_deg": 15.0,
        "anode_symbol": "W",
        "focal_spot_diameter_mm": 0.05,
        "tube_collimator_radius_mm": 0.15,
        "focal_spot_to_sample_distance_mm": 140.0,
        "tube_window_to_sample_distance_mm": 130.0,
        "tube_window_to_virtual_collimator_distance_mm": 100.0,
        "elevation_deg": 90.0,
        "azimuth_deg": 90.0,
        "tube_type": "reflection",
        "target_thickness_um": 0.0,
        "window": {
            "name": "tube_window",
            "material": "G4_Be",
            "thickness_mm": 0.001,
        },
        "spekpy_filters": [
            {"element": "Al", "thickness_mm": 0.5},
        ],
        "geant4_filters": [],
    },
    "detector": {
        "name": "detector",
        "shape": "Circular",
        "material": "G4_Si",
        "radius_mm": 4.0,
        "width_mm": 8.0,
        "height_mm": 8.0,
        "thickness_mm": 1.0,
        "distance_mm": 17.0,
        "elevation_deg": 90.0,
        "azimuth_deg": 50.0,
        "housing": {
            "enabled": True,
            "name": "detector_housing",
            "aperture_shape": "Circular",
            "aperture_radius_mm": 5.0,
            "aperture_width_mm": 10.0,
            "aperture_height_mm": 10.0,
            "detector_clearance_mm": 2.0,
            "housing_wall_thickness_mm": 1.0,
            "cavity_wall_thickness_mm": 1.0,
            "housing_material": "G4_Al",
            "cavity_material": "G4_W",
            "inner_cavity_medium_material": "G4_Galactic",
            "window_material": "G4_Be",
            "window_thickness_mm": 0.01,
        },
        "internal_masks": [
            {
                "name": "Ti_mask",
                "aperture_shape": "Circular",
                "aperture_radius_mm": 3.09,
                "outer_radius_mm": 4.0,
                "aperture_width_mm": 5.0,
                "aperture_height_mm": 5.0,
                "outer_width_mm": 8.0,
                "outer_height_mm": 8.0,
                "length_mm": 0.025,
                "material": "G4_Ti",
                "distance_mm": 0.10,
            },
            {
                "name": "Al_mask",
                "aperture_shape": "Circular",
                "aperture_radius_mm": 3.09,
                "outer_radius_mm": 4.0,
                "aperture_width_mm": 5.0,
                "aperture_height_mm": 5.0,
                "outer_width_mm": 8.0,
                "outer_height_mm": 8.0,
                "length_mm": 0.075,
                "material": "G4_Al",
                "distance_mm": 0.30,
            },
            {
                "name": "W_mask",
                "aperture_shape": "Circular",
                "aperture_radius_mm": 3.09,
                "outer_radius_mm": 4.0,
                "aperture_width_mm": 5.0,
                "aperture_height_mm": 5.0,
                "outer_width_mm": 8.0,
                "outer_height_mm": 8.0,
                "length_mm": 0.10,
                "material": "G4_W",
                "distance_mm": 0.50,
            },
        ],
        "filters": [],
        "collimators": [],
    },
    "physics": {
        "interaction_bias_use": True,
        "secondary_splitting_use": True,
        "flu_use": True,
        "auger_use": False,
        "pixe_use": False,
        "ignore_cut_use": True,
        "flu_dataset_name": "ANSTO",
        "maximum_energy": 1000.0,
        "phot_factor": 100,
        "compt_factor": 100,
        "rayl_factor": 100,
        "electron_cut": 0.01,
        "gamma_cut": 0.01,
        "positron_cut": 0.01,
        "proton_cut": 0.01,
    },
    "run": {
        "run_name": "full_xrf_example",
        "beam_on": 10_000_000,
        "number_of_thread": 15,
        "print_display": 100_000,
        "vis_beam_on": 100,
        "vis_threads": 1,
    },
    "noise": {
        "current_ma": 1.0,
        "live_time_s": 30.0,
        "fwhm_ev": 140.0,
        "fwhm_energy_kev": 5.9,
        "pile_up_window_us": 0.1,
        "detector_gain_kev": 0.025,
        "detector_zero_offset": 0.0,
        "fano_factor": 0.115,
        "pair_creation_energy_ev": 3.6,
        "mca_channels": 2048,
        "chunk_size": 3_000_000,
        "number_of_buckets": 65,
    },
}


def fresh_default_config():
    return deepcopy(DEFAULT_CONFIG)
